---
title: <center> Wine Quality Dataset - Statistical Learning Report </center>
author: <br></br> <br></br> <right> L. Clissa, A. Macaluso e L. Pestarino </right>
date: 5 July 2018
output: 
  html_document:
   default
---

<style>
body {
text-align: justify}
</style>

<br></br>
<br></br>


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

setwd( rprojroot::find_rstudio_root_file() )

source( 'code/Utils.R')
SEED = 12344321
source( 'code/020_Pre_processing.R')

library('ggplot2')
library('plotly')
library('DT')
#source( "030_DATA_VIZ_CUSTOM.R")
```

```{r child = '130_Index.Rmd'}
```


```{r child = '150_Introduction.Rmd'}
```


```{r child = '200_Classification.Rmd'}
```


```{r child = '210_LPM.Rmd'}
```


```{r child = '220_LDA.Rmd'}
```


```{r child = '230_QDA.Rmd'}
```


```{r child = '240_LOGISTIC_REGRESSION.Rmd'}
```


```{r child = '250_REGULARISED_METHODS.Rmd'}
```


```{r child = '260_KNN.Rmd'}
```

 
```{r child = '270_GAM.Rmd'}
```



```{r child = '280_CART.Rmd'}
```


```{r child = '290_RF.Rmd'}
```


```{r child = '300_Conclusion.Rmd'}
```